import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Sparkles, Zap, Shield, MessageSquare } from 'lucide-react'

type LandingPageProps = {
  onStartSession: () => void
  onStopSession: () => void
  isSessionActive: boolean
  sessionCountdown: number
  navigate: (tab: string) => void
}

const formatCountdown = (value: number) => {
  const safe = Math.max(0, value)
  const minutes = Math.floor(safe / 60)
  const seconds = safe % 60
  return `${minutes}:${seconds.toString().padStart(2, '0')}`
}

const features = [
  {
    icon: Sparkles,
    title: 'AI Triage',
    description: 'Classifies every query and drafts auto-responses in seconds.',
  },
  {
    icon: Zap,
    title: 'Real-time simulator',
    description: 'Stream fresh inbound messages using OpenAI-powered generators.',
  },
  {
    icon: Shield,
    title: 'Routing & urgency',
    description: 'Score sentiment + severity, route to the right department.',
  },
  {
    icon: MessageSquare,
    title: 'Multi-channel',
    description: 'WhatsApp, Twitter, Email, Web chat — all in one inbox.',
  },
]

export function LandingPage({
  onStartSession,
  onStopSession,
  isSessionActive,
  sessionCountdown,
  navigate,
}: LandingPageProps) {
  return (
    <div className="mx-auto flex max-w-5xl flex-col gap-8 px-6 py-12">
      <section className="text-center">
        <p className="text-xs font-semibold uppercase tracking-[0.4em] text-muted-foreground">
          QueryFlow AI
        </p>
        <h1 className="mt-3 text-4xl font-semibold leading-tight text-foreground md:text-5xl">
          Route every customer query with live AI copilots.
        </h1>
        <p className="mt-4 text-lg text-muted-foreground">
          Spin up a demo contact center where OpenAI classifies intent, sentiment, urgency, and auto-assigns work across teams.
        </p>
        <div className="mt-6 flex flex-wrap justify-center gap-3">
          <Button size="lg" onClick={() => navigate('user-console')}>
            Enter User Console
          </Button>
          <Button size="lg" variant="secondary" onClick={() => navigate('routing')}>
            View Routing Overview
          </Button>
          <Button size="lg" variant="ghost" onClick={() => navigate('admin')}>
            Open Admin Inbox
          </Button>
        </div>
      </section>

      <section className="grid gap-4 md:grid-cols-2">
        {features.map(({ icon: Icon, title, description }) => (
          <Card key={title} className="border border-dashed">
            <CardHeader className="flex flex-row items-center gap-3">
              <div className="rounded-full bg-primary/10 p-2 text-primary">
                <Icon className="h-5 w-5" />
              </div>
              <CardTitle className="text-lg">{title}</CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>{description}</CardDescription>
            </CardContent>
          </Card>
        ))}
      </section>

      <section className="rounded-3xl border bg-gradient-to-br from-slate-900 via-blue-900/80 to-slate-900 p-8 text-white">
        <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div>
            <p className="text-sm uppercase tracking-[0.4em] text-blue-200/80">Live simulator</p>
            <h2 className="mt-2 text-2xl font-semibold">Start an AI session</h2>
            <p className="text-sm text-blue-100/80">
              Stream synthetic customer conversations generated by OpenAI, routed through the exact same pipeline as real users.
            </p>
          </div>
          <div className="flex flex-col gap-2 md:text-right">
            <Button
              size="lg"
              onClick={isSessionActive ? onStopSession : onStartSession}
              className={
                isSessionActive
                  ? 'border border-blue-200 bg-white/90 text-blue-900 transition hover:bg-white'
                  : 'bg-gradient-to-r from-blue-500 via-sky-500 to-cyan-400 text-white shadow-lg hover:opacity-90'
              }
            >
              {isSessionActive ? `Stop session (${formatCountdown(sessionCountdown)})` : 'Start session'}
            </Button>
            <p className="text-xs text-blue-100/80">
              {isSessionActive
                ? `Session auto-stops in ${formatCountdown(sessionCountdown)}`
                : 'Generates a fresh multi-channel query every few seconds.'}
            </p>
          </div>
        </div>
      </section>
    </div>
  )
}

